### ISSUE TITLE
Accessory not added after adding platform configuration

### ISSUE THREAD

**Issue by bortk** [nitaybz/homebridge-electra-smart#2]
Hi,
I installed the plugin and got imei and token using electra-extract.
After updating the configuration, I can't see new device in homekit.
I'm getting this error in the log:
[ElectraSmart] ERR: Could NOT get Session ID: Token not found
Thanks

**Comment by nitaybz** [comment]
seems like the token is missing or incorrect, try to run the electra-extract again and make sure you fetch only the value without any spaces around or something like that

**Comment by bortk** [comment]
I tried again several times. I'm sure that the token is correct.
I'm running the electra app on iPhone and not on Android. I saw that you emulate Android client in the request.

I tried to debug and I see that I'm getting this in the http response: "Token not found"

**Comment by nitaybz** [comment]
It doesn't matter the android device I'm emulating.... is it possible that you used different phone number when you registered those devices?

**Comment by nitaybz** [comment]
Please share your config
