### ISSUE TITLE
Session ID is NULL when trying use the plugin

### ISSUE THREAD

**Issue by galbala** [nitaybz/homebridge-electra-smart#4]
While using the plugin, after registration with phone and setting polling interval to 300- still getting the “Intruder Lockout” error message.
After setting “debug mode” to true- i see there are two tries of doing operation but in the first time “Session ID: null” message appears, and in second try, the intruder error message appears.

**Comment by DorsayIL** [comment]
Hi!
You need to be more modest :) and request telemetry every 1-2 minutes instead of 1-2 seconds

Regards...
Vayosoft developers team :)

**Comment by galbala** [comment]
But.... according to the readme file PollingInterval is in seconds- so it’s ok as I understand.
Even when disabling the PollingIntercval (setting to 0)
I still get the error.

**Comment by galbala** [comment]
But.... according to the readme file PollingInterval is in seconds- so it’s ok as I understand.
Even when disabling the PollingIntercval (setting to 0)
I still get the error

**Comment by hillaliy** [comment]
Same for me. I get the message "intruder lockout".
even if I set the polling interval to max (600)
I think Electra made changes on the server.
I try to use Home-Assistant Electra Smart, the same problem.

**Comment by nitaybz** [comment]
Hey Guys!

I think I solved it in the last version I released (v1.0.10).... please get new token and feel free to set any interval you want as it should not bring the "intruder lockout" again....

please post back....

**Comment by hillaliy** [comment]
from yesterday it's work just fine.

**Comment by nitaybz** [comment]
users are reporting it is working now... so closing...
